smartweb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
  get 'profile' => 'registrations#show'
end

  root to: "pages#index"
  resources :courses do
    get 'manage', on: :collection
    post 'resolve', on: :member
    post 'report', on: :member
    resources :payments do
      post 'validate', on: :collection
    end
    
    resources :students do
      post 'validate', on: :member
    end
    resources :lectures
    resources :supplies
  end

  resources :course_demands do 
    get 'manage', on: :collection
  end


  resources :recomendations


end

smartweb/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :resolve, :report]
  before_action :authenticate_user!, except: [:index, :show]

  layout false

  def index
    @courses = can?(:manage, Course) ? Course.all : Course.visible
    if params[:filter].present?
      @courses = @courses.where("LOWER(courses.name) LIKE '%#{params[:filter].downcase}%'")
    end
    
    @courses = @courses.order(date: :desc).page(params[:page])

    render layout: 'application'
  end

  def manage
    @courses = can?(:manage, Course) ? Course.all : Course.mine(current_user)
    render layout: 'application'
  end

  def show
    render layout: 'application'
  end

  def new 
    @course = Course.new
    @course.course_demand_id = params[:course_demand_id] if params[:course_demand_id] && CourseDemand.find(params[:course_demand_id]).present?
    render :edit   
  end

  def create
    @course = Course.new(course_params)
    @course.teacher = current_user
    if @course.save
      redirect_to @course, notice: t('controllers.courses.create.success')
    else
      render action: :edit
    end
  end

  def edit 
  end

  def report
    @course.reported = true;
    @course.save
    redirect_to @course, notice: 'Hecho con éxito'
  end

  def update
    if @course.update(course_params)
      redirect_to root_path, notice: t('controllers.courses.update.success') 
    else
      render action: :edit
    end
  end


  def resolve
    @course_demand = CourseDemand.find(params[:course_demand][:course_demand_id])
    @course.course_demand = @course_demand
    @course.save!
    redirect_to @course, notice: t('controllers.course_demands.update.success') 
  end

  def destroy
    @course.destroy
    redirect_to root_path, notice: t('controllers.courses.destroy.success')
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :short_description, :price, :cover, :course_demand_id, :hidden, :date, categories:[])
    end
end

smartweb/app/helpers/courses_helper.rb
module CoursesHelper
end

smartweb/app/views/courses/_admin_list.html.erb
<div>
  <% @courses.each do |course| %>
    <div class="course">
      <div>
        <p><span class="bold"><%= course.name %></span></p>
        <p><%= course.short_description %></p>
        <p><%= course.categories.map(&:value).to_sentence %></p>
      </div>
      <div>
        
        <%= link_to 'eliminar', course, method: 'DELETE', title: t('views.courses._admin_list.destroy.link'), confirm: t('views.courses._admin_list.destroy.confirm') %>
        <%= link_to 'editar', edit_course_path(course),        title: t('views.courses._admin_list.edit'), rel:'modal:open' %>
        <%= link_to 'Clases', new_course_lecture_path(course), title: t('views.courses._admin_list.edit'), rel:'modal:open' %>
        <%= link_to 'Alumnos', course_students_path(course), rel:'modal:open' %>


          <%= form_tag resolve_course_path(course) do %>
             <p>Resuelve la siguiente demanda: <%= collection_select(:course_demand, :course_demand_id, CourseDemand.all, :id, :name, prompt: true, include_blank: false) %> <%= submit_tag %></p>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to t('views.courses._admin_list.new'), new_course_path, rel: 'modal:open' %>

smartweb/app/views/courses/_list.html.erb
 <div>
  <% @courses.each do |course| %>
    <div class="course">
      <div class="course-data">
        <span class="bold"><%= course.name %></span> por
        <%= course.teacher.name %>
      </div>
      <div class="course-data">
        <%= l course.date, format: :long if course.date.present? %>
      </div>
      <div class="course-price">
        <%= (course.price / 100.0).round(2).to_s + ' €' if course.price %>
      </div>
      <div class="course-data">
        <%= image_tag course.cover.url, height:'250' %>
      </div>
      <div class="course-data">
        <div>
          <p><%= course.short_description %></p>
          <%= link_to 'Detalles', course %> 
          <%= (link_to 'Matricularse', course_students_path(course), method: :post) if can?(:enroll, Course) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

smartweb/app/views/courses/edit.html.erb
<% content_for :title do %>
  <%= @course.id ? t('views.courses.edit.form.title.edit') : t('views.courses.edit.form.title.new') %>
<% end %>

<%= simple_form_for @course, html: { class: ""} do |f| %>
  <div>
    <%= f.input :course_demand_id, as: :hidden %>
  </div>
  <div>
    <%= f.input :name %>
  </div>
  <div> 
    <%= f.input :date %>
  </div>
  <div> 
    <%= f.input :hidden %>
  </div>
  <div> 
    <%= f.input :price %>
  </div>
  <div> 
    <%= f.input :short_description %>
  </div>
  <div>
    <%= f.input :description, :input_html => { :rows => 8 } %>
  </div>
  <div>
    <%= f.input :cover %>  
  </div>
  <div>
    <%= f.input :categories, :as => :check_boxes %>  
  </div>
  <div>
    <%= f.button :submit %>
  </div>
<% end %>

smartweb/app/views/courses/index.html.erb
<section>
  <div>
    <h1>Listado de los últimos cursos de los usuarios</h1>
    <div>
      <%= render 'courses/list' %>
    </div>  
  </div>
</section>

smartweb/app/views/courses/manage.html.erb
<section>
  <div>
    <h1><span>Gestionar mis cursos<span></h1>
    <div>
      <%= render 'courses/admin_list' %>
    </div>  
  </div>
</section>

smartweb/app/views/courses/show.html.erb
<h1> Detalles del curso </h1>
  <div class="basic_data">
    <p>Nombre: <%= @course.name %></p>
    <p>Descripción: <%= @course.description %></p>
    <p>Precio: <%= @course.price.to_i / 100.0 %></p>
    <p>Minutos: <%= @course.minutes %></p>
    <p>Alumnos matriculados: <%= @course.students.valid.count %></p>
    <p><%= image_tag @course.cover, class:'avatar' %></p>
  </div>
  


  <div class="course-data">
     <div>
      <% student = current_user ? @course.student_by(current_user) : nil  %>
      <% if student %>
         <%= student.current_state %>
         <% unless student.enrolled? || @course.free? %>
           <%= link_to 'Pagar la matrícula', course_payments_path(@course) %>
         <% end %>
      <% else %>
        <%= (link_to 'Matricularse', course_students_path(@course), method: :post) if can?(:enroll, @course)  %>
      <% end %>
    </div>
  </div>


  <ul>
    <% @course.lectures.each do |lecture| %>
      <li>
        Clase: <%= lecture.title %><br/>
        Hora: <%= l lecture.start_at, format: :long if lecture.start_at %>
      <%= link_to '#_go_to_lecture', course_lecture_path(@course, lecture) %>
    </li>
    <% end %>
  </ul>

<% if @course.reported %>
  Reportado como inadecuado
<% else %>
  <%= link_to 'Reportar cursos inadecuado', report_course_path(@course), method: :post %>
<% end %>