smartweb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
  get 'profile' => 'registrations#show'
end

  root to: "pages#index"
  resources :courses do
    get 'manage', on: :collection
    post 'resolve', on: :member
    post 'report', on: :member
    resources :payments do
      post 'validate', on: :collection
    end
    
    resources :students do
      post 'validate', on: :member
    end
    resources :lectures
    resources :supplies
  end

  resources :course_demands do 
    get 'manage', on: :collection
  end


  resources :recomendations


end

smartweb/app/models/course_demand.rb
class CourseDemand < ActiveRecord::Base

  belongs_to :user

  has_many :courses, dependent: :nullify
  
  scope :open, -> {where.not(workflow_state: "resolved")}

  #Enumerize -> categories
  extend Enumerize
  serialize :categories, Array
  enumerize :categories, in: [:tecnology, :arts, :healt, :design], multiple: true

  #FriendlyId -> name and slug
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Workflow
  include Workflow
  workflow do
    state :publish do
      event :resolve, :transitions_to => :resolved
    end
    state :resolved 
  end

end

smartweb/app/controllers/course_demands_controller.rb
class CourseDemandsController < ApplicationController
  before_action :set_course_demand, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout false

  def index
    @course_demands = CourseDemand.all 
    if params[:filter].present?
      @course_demands = @course_demands.where("LOWER(course_demands.name) LIKE %#{params[:filter].downcase}%")
    end
    
    @course_demands = @course_demands.order(created_at: :desc).page(params[:page])

    render layout: 'application'
  end

  def manage
    @course_demands = CourseDemand.all
    render layout: 'application'
  end

  def show
    render layout: 'application'
  end

  def new 
    @course_demand = CourseDemand.new
    render :edit   
  end

  def create
    @course_demand = CourseDemand.new(course_demand_params)
    @course_demand.user = current_user
    if @course_demand.save
      redirect_to root_path, notice: t('controllers.course_demands.create.success')
    else
      render action: :edit
    end
  end

  def edit 
  end

  def update
    if @course_demand.update(course_demand_params)
      redirect_to root_path, notice: t('controllers.course_demands.update.success') 
    else
      render action: :edit
    end
  end

  def destroy
    @course_demand.destroy
    redirect_to root_path, notice: t('controllers.course_demands.destroy.success')
  end

  private
    def set_course_demand
      @course_demand = CourseDemand.friendly.find(params[:id])
    end

    def course_demand_params
      params.require(:course_demand).permit(:name, :description, :short_description, :cover, categories:[])
    end
end

smartweb/app/views/course_demands/_admin_list.html.erb
<h5>
  <span><%= CourseDemand.model_name.human %></span>
</h5>

 <div>
  <% @course_demands.each do |course_demand| %>
    <div>
      <div>
        <%= link_to course_demand.name, course_demand %>
        <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, course_demand, method: 'DELETE', title: t('views.courses._admin_list.destroy.link'), confirm: t('views.courses._admin_list.destroy.confirm') %>
        <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_course_demand_path(course_demand), title: t('views.courses._admin_list.edit'), rel:'modal:open' %>
      </div>
      <div>
        <div>
          <p><%= course_demand.description %></p>
          <p><%= course_demand.categories.map(&:value).to_sentence %></p>
          <% course_demand.courses.each do |course| %>
             <%= link_to course.name, course %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to t('views.courses._admin_list.new'), new_course_demand_path, rel: 'modal:open' %>

smartweb/app/views/course_demands/_list.html.erb
 <div>
  <% @course_demands.each do |course_demand| %>
    <div class="course">
      <div>
        <p><%= course_demand.name %></p>
          <% course_demand.courses.each do |course| %>
           <p><% link_to course.name, course %></p>
          <% end %>
      </div>
      <div>
        <p><%= l course_demand.created_at, format: :long if course_demand.created_at.present? %></p>
      </div>
      <div>
        <div>
          <p><%= course_demand.description %></p>
        </div>
        <div>
        <% if course_demand.courses.count > 0 %>
          Problemática resuelta por los siguientes cursos:
        <% end %>
        <% course_demand.courses.each do |course| %>
             <p><%= link_to course.name, course %></p>
          <% end %>
          <p><%= link_to 'Resolver demanda', new_course_path(course_demand_id: course_demand.id), rel:'modal:open' if current_user %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

smartweb/app/views/course_demands/edit.html.erb
<% content_for :title do %>
  <%= @course_demand.id ? t('views.courses.edit.form.title.edit') : t('views.courses.edit.form.title.new') %>
<% end %>

<%= simple_form_for @course_demand, html: { class: ""} do |f| %>
  <div>
    <%= f.input :name %>
  </div>
  <div>
    <%= f.input :description, :input_html => { :rows => 8 } %>
  </div>
  <div>
    <%= f.input :categories, :as => :check_boxes %>  
  </div>
  <div>
    <%= f.button :submit %>
  </div>
<% end %>

smartweb/app/views/course_demands/index.html.erb
<section>
  <div>
    <h1>Solicitudes de cursos</h1>
    <div>
      <%= render 'course_demands/list' %>
    </div>  
  </div>
</section>

smartweb/app/views/course_demands/manage.html.erb
<section>
  <div>
    <h2><span><%= t('views.courses.manage.title') %><span></h2>
    <div>
      <%= render 'course_demands/admin_list' %>
    </div>  
  </div>
</section>

smartweb/app/views/course_demands/show.html.erb
<div class="basic_data">
  <p>#_course_name: <%= @course_demand.name %></p>
  <p>#_coruse_description: <%= @course_demand.description %></p>
</div>

<ul>
  <% @course_demand.courses.each do |course| %>
  <% if course.pricce == 0  || enroll_since.nil? enroll_since< Time.now %>
       <p> #_join_to: <%= link_to '#_join_it', course_students_path(course), method: :post   %></p>
     <% end %>
    <li><%= link_to course.name, course %></li>
  <% end %>
</ul>