smartweb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
  get 'profile' => 'registrations#show'
end

  root to: "pages#index"
  resources :courses do
    get 'manage', on: :collection
    post 'resolve', on: :member
    post 'report', on: :member
    resources :payments do
      post 'validate', on: :collection
    end
    
    resources :students do
      post 'validate', on: :member
    end
    resources :lectures
    resources :supplies
  end

  resources :course_demands do 
    get 'manage', on: :collection
  end


  resources :recomendations


end

smartweb/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :student


  validates :transaction_number, uniqueness: true
  validates :amount, :numericality => { :greater_than => 0 }
  validates :valid, presence: true

  before_validation :set_transaction_number, on: :create



  private
    def set_transaction_number
      self.transaction_number = student.id.to_s + '0' + Time.now.to_i.to_s 
    end

end

smartweb/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course

  def index
  end

  def validate
  end

   private
    
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end


end

smartweb/app/helpers/payments_helper.rb
module PaymentsHelper
end

smartweb/app/views/payments/index.html.erb
<h1> Debe ingresar <%= @course.price.to_i / 100.0 %> € en la siguiente cuenta </h1>


<p>Titular: <%= @course.teacher.name %></p>
<p>Nº Cuenta; 2140623456</p>
<p>Concepto: <%= current_user.email %> </p>


cuando lo haya echo puede entregar aqui el justifcante para acelerar las cosas


<%= form_tag validate_course_payments_path(@course) do %>

  <%= file_field_tag :deposit %>
  <%= submit_tag %>

<% end %>