smartweb/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
  get 'profile' => 'registrations#show'
end

  root to: "pages#index"
  resources :courses do
    get 'manage', on: :collection
    post 'resolve', on: :member
    post 'report', on: :member
    resources :payments do
      post 'validate', on: :collection
    end
    
    resources :students do
      post 'validate', on: :member
    end
    resources :lectures
    resources :supplies
  end

  resources :course_demands do 
    get 'manage', on: :collection
  end


  resources :recomendations


end

smartweb/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   
    cannot :manage, :all



    if user
      can [:create], Recomendation

      if user.role == :admin
        can :manage, :all
      else
        can [:read, :create, :enroll],    Course
        cannot :enroll,          Course, teacher_id: user.id 
        can [:update, :destroy], Course, teacher_id: user.id 
        can [:show],             Course, students: { workflow_state: "enrolled", user_id: user.id }
        can [:show],             Course, teacher_id: user.id 

        can [:show],          Lecture do |lecture|
          (lecture.start_at.nil? || lecture.start_at < Time.now) &&
          user.students.where("workflow_state = 'enrolled'").pluck(:course_id).include?(lecture.course_id)
        end
         
        can [:create, :read, :update, :destroy], CourseDemand, user_id: user.id 
      end
    end


  end
end

smartweb/app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :teacher, class_name: 'User'
  belongs_to :course_demand

  has_many :students, dependent: :destroy
  has_many :supplies, dependent: :destroy
  has_many :lectures, dependent: :destroy
  has_and_belongs_to_many :users, join_table: :students

  validates :name, presence: true
  validates :teacher, presence: true
  validates :short_description, presence: true

  scope :visible, -> {where.not(hidden: true)}

  #Carrierwave -> cover
  mount_uploader :cover, CoverUploader

  #Enumerize -> categories
  extend Enumerize
  serialize :categories, Array
  enumerize :categories, in: [:tecnology, :arts, :healt, :design], multiple: true

  #FriendlyId -> name and slug
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Workflow
  include Workflow
  workflow do
    state :publish do
      event :start, :transitions_to => :ongoing
    end
    state :ongoing do
      event :finish, :transitions_to => :finished
    end
    state :finished 
  end

  #methods
  def minutes
    self.lectures.sum(:duration)
  end

  def self.mine user 
    user ? Course.where(teacher_id: user.id) : []
  end

  def free?
    self.price == 0
  end

  def student_by user
    Student.where(course_id: self.id, user_id: user.id).first  
  end
end

smartweb/app/models/course_demand.rb
class CourseDemand < ActiveRecord::Base

  belongs_to :user

  has_many :courses, dependent: :nullify
  
  scope :open, -> {where.not(workflow_state: "resolved")}

  #Enumerize -> categories
  extend Enumerize
  serialize :categories, Array
  enumerize :categories, in: [:tecnology, :arts, :healt, :design], multiple: true

  #FriendlyId -> name and slug
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Workflow
  include Workflow
  workflow do
    state :publish do
      event :resolve, :transitions_to => :resolved
    end
    state :resolved 
  end

end

smartweb/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :course


  validates :course, presence: true
  #FriendlyId -> title and slug
  extend FriendlyId
  friendly_id :title, use: :slugged


end

smartweb/app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :student


  validates :transaction_number, uniqueness: true
  validates :amount, :numericality => { :greater_than => 0 }
  validates :valid, presence: true

  before_validation :set_transaction_number, on: :create



  private
    def set_transaction_number
      self.transaction_number = student.id.to_s + '0' + Time.now.to_i.to_s 
    end

end

smartweb/app/models/recomendation.rb
class Recomendation < ActiveRecord::Base
  belongs_to :from_user, class_name: 'User'
  belongs_to :to_user, class_name: 'User'

  has_and_belongs_to_many :courses_recomendations

  validates :to_user, presence: true
end

smartweb/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

  has_many :payments
  
  validates :user, uniqueness: { scope: :course, allow_nil: false}
  validates :course, presence: true
  
  scope :valid, -> {where(workflow_state: "enrolled")}

  # Workflow
  include Workflow
  workflow do
    state :pending_approbal do
      event :paid, transitions_to: :enrolled
      event :accept, transitions_to: :enrolled
    end
    state :enrolled
  end

end

smartweb/app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :course
end

smartweb/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :students, dependent: :destroy
  has_many :course_demands, dependent: :destroy
  has_many :courses, foreign_key: :teacher
  has_and_belongs_to_many :courses, join_table: 'students'

  #Enumerize -> categories
  extend Enumerize
  enumerize :role, in: [:admin]
  
end

smartweb/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def dev
  end
  
end

smartweb/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def manage_roles
    authorize! :manage, User
    @user = User.find(params[:id])
    @user.role = params[:user][:role]
    @user.save!
  end

end

smartweb/app/helpers/api_helper.rb
module ApiHelper
  def paginate_json(collection)
    current_page_num = collection.current_page
    last_page_num = collection.total_pages

    {
      :first => first_page_json,
      :previous => previous_page_json(current_page_num),
      :self => current_page_json(current_page_num),
      :next => next_page_json(current_page_num, last_page_num),
      :last => last_page_json(last_page_num)
    }
  end

  def first_page_json
    { :href => url_for(:page => 1) }
  end

  def previous_page_json(current_page_num)
    return nil if current_page_num <= 1
    { :href => url_for(:page => current_page_num-1) }
  end

  def current_page_json(current_page_num)
    { :href => url_for(:page => current_page_num) }
  end

  def next_page_json(current_page_num, last_page_num)
    return nil if current_page_num >= last_page_num
    { :href => url_for(:page => current_page_num+1) }
  end

  def last_page_json(last_page_num)
    { :href => url_for(:page => last_page_num) }
  end
end

smartweb/app/helpers/application_helper.rb
module ApplicationHelper
end

smartweb/app/helpers/courses_helper.rb
module CoursesHelper
end

smartweb/app/helpers/items_helper.rb
module ItemsHelper
end

smartweb/app/helpers/lectures_helper.rb
module LecturesHelper
end

smartweb/app/helpers/pages_helper.rb
module PagesHelper
end

smartweb/app/helpers/payments_helper.rb
module PaymentsHelper
end

smartweb/app/helpers/students_helper.rb
module StudentsHelper
end

smartweb/app/helpers/supplies_helper.rb
module SuppliesHelper
end

smartweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartweb</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="page">
	<div class="bounded-content">
		<div class="menu">
			<ul>
				<li>
					<%= form_tag courses_path, method: :get do %>
			  	<%= text_field_tag :filter %>
			  	<%= submit_tag 'Buscar' %>
					<% end %>
				</li>
				<li><%= link_to 'Asistir a cursos', courses_path %></li>
				<li><%= link_to 'Mis cursos', manage_courses_path %></li>
				<li>
					<% if current_user %>
				  	<%= link_to 'Solicitar un curso', new_course_demand_path, rel:'modal:open'  %>
					<% else %>
				  	<%= link_to 'Solicitar un curso', new_course_demand_path  %>
					<% end %>
				</li>
				<li><%= link_to 'Mis solicitudes', course_demands_path %></li>
				<li><%= link_to 'Mis recomendaciones', recomendations_path %></li>
		    <li><% if current_user %>
		    <%= link_to 'Cerrar Sesión', destroy_user_session_path, :method => :delete if current_user %>
		    <%= link_to 'Perfil', profile_path %>
		    <% end %>
		    </li>
			</ul>
		</div>
		<%= yield %>
	</div>
</div>

</body>
</html>

smartweb/app/views/pages/index.html.erb
<h1> Sistema Integral de Formación Online de Corta Duración </h1>
<p> Plataforma cuyo objetivo principal es poner en contacto a expertos en materias de diversa índole con personas interesadas que sirva como base de un espacio dinámico común donde compartir y solicitar actividades formativas</p>

<div id="functionalities" class="row list">
	<ul>
		<li>
			<span class="bold">Alta y gestión de usuarios</span>
			<ul>
				<li>Roles maestro, alumno y moderador. Se pueden dar a la vez</li>
			</ul>
		</li>
	</ul>
	<ul>
		<li>
			<span class="bold">Creación de cursos</span>
			<ul>
				<li>Creación de cursos</li>
				<li>Creación de clases (Máx 5 min de duración y tema completo)</li>
				<li>Asignación de recursos y material didáctico</li>
				<li>Gestión completa de fechas y clases</li>
			</ul>
		</li>
	</ul>
	<ul>
		<li>
			<span class="bold">Matriculación en cursos</span>
			<ul>
				<li>Pago de tasas por curso completo a través de transferencia bancaria</li>
				<li>Periodos de matriculación establecidos por el profesor</li>
			</ul>
		</li>
	</ul> 
	<ul>
		<li>
			<span class="bold">Demanda de cursos</span>
			<ul>
				<li>Publicación en la plataforma por temas en los que está interesado en recibir formación</li>
				<li>Creación de cursos en base a estas demandas</li>
				<li>Asignación de otros cursos que cumplen con la temática demandada</li>
			</ul>
		</li>
	</ul>
	<ul>
		<li>
			<span class="bold">Recomendación de cursos</span>
			<ul>
				<li>Posibilidad de enviarse entre usuarios de la plataforma ciertos cursos que pueden ser de su interés</li>
				<li>Planteada la posibilidad de recomendaciones automáticas en base a un algoritmo de recomendación</li>
			</ul>
		</li>
	</ul>
	<ul>
		<li>
			<span class="bold">Reporte de cursos maliciosos</span>
			<ul>
				<li>Notificación por parte de usuarios de cursos considerados de mal gusto o que no cumpla los requisitos de la plataforma</li>
			</ul>
		</li>
	</ul>
</div>

<div class="row list">
	<ul>
		<li>
			<span class="bold">Características técnicas</span>
			<ul>
				<li>Plataforma ruby on rails</li>
				<li>Base de datos Postgresql</li>
				<li>Api RESTFUL</li>
			</ul>
		</li>
	</ul>
</div>